CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS hunt_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL DEFAULT 'OPS-' || to_char(now(),'YYYYMMDDHH24MISS'), config JSONB NOT NULL DEFAULT '{}'::jsonb, status TEXT NOT NULL DEFAULT 'setup', created_by_role TEXT NOT NULL DEFAULT 'admin', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), session_id UUID REFERENCES hunt_sessions(id) ON DELETE CASCADE, filename TEXT NOT NULL, doc_type TEXT DEFAULT 'Mission Document', minio_key TEXT, parsed BOOLEAN DEFAULT false, indexed BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), event_id TEXT UNIQUE NOT NULL, session_id UUID REFERENCES hunt_sessions(id) ON DELETE CASCADE, agent TEXT NOT NULL, severity TEXT NOT NULL, title TEXT NOT NULL, snippet TEXT DEFAULT '', explanation TEXT DEFAULT '', enrichment JSONB DEFAULT '[]'::jsonb, tags JSONB DEFAULT '[]'::jsonb, recommended_next_question TEXT DEFAULT '', raw_log_sample TEXT DEFAULT '{}', confidence NUMERIC DEFAULT 0, status TEXT DEFAULT 'new', requires_human_approval BOOLEAN DEFAULT true, suggested_case_link UUID, asom_draft JSONB, metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS cases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), case_id TEXT UNIQUE NOT NULL, session_id UUID REFERENCES hunt_sessions(id) ON DELETE CASCADE, name TEXT NOT NULL, owner TEXT DEFAULT 'Unassigned', narrative_summary TEXT DEFAULT '', ioc_tags JSONB DEFAULT '[]'::jsonb, status TEXT DEFAULT 'open', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS case_events (case_id UUID REFERENCES cases(id) ON DELETE CASCADE, event_id UUID REFERENCES events(id) ON DELETE CASCADE, PRIMARY KEY(case_id,event_id));
CREATE TABLE IF NOT EXISTS asom_lines (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), session_id UUID REFERENCES hunt_sessions(id) ON DELETE CASCADE, line_no INT NOT NULL, title TEXT NOT NULL, status TEXT DEFAULT 'pending', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), session_id UUID REFERENCES hunt_sessions(id) ON DELETE CASCADE, ip TEXT NOT NULL, hostname TEXT, owner TEXT, criticality TEXT DEFAULT 'unknown', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS custom_agents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, role_string VARCHAR(100) NOT NULL UNIQUE, description TEXT, telemetry_source VARCHAR(50) NOT NULL, tier VARCHAR(20) DEFAULT 'network', severity_default VARCHAR(20) DEFAULT 'medium', confidence_threshold FLOAT DEFAULT 0.6, detection_focus TEXT NOT NULL, key_fields JSONB DEFAULT '[]'::jsonb, tag_rules JSONB DEFAULT '[]'::jsonb, system_prompt_override TEXT, enabled BOOLEAN DEFAULT false, created_by VARCHAR(100), version INTEGER DEFAULT 1, parent_id UUID REFERENCES custom_agents(id), archived_at TIMESTAMPTZ, last_run_at TIMESTAMPTZ, total_events_generated INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
